# Site settings
title: Yan (Nicole) Yang
author:
  name: Yan (Nicole) Yang 2023
  email: yan.yang@queensu.ca
description: "143 Union St, Kingston, ON K7L 3N6"

# Build settings
remote_theme: jekyll/minima
